### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by alexcarpenter** [alexcarpenter/frontend-foundations#22]

**Comment by shoutoutloud** [comment]
Hi. Can I work on this issue?

**Comment by alexcarpenter** [comment]
@shoutoutloud Of course!

**Comment by shoutoutloud** [comment]
Thank you. So what do you need in the page?

**Comment by alexcarpenter** [comment]
Closed in https://github.com/alexcarpenter/frontend-foundations/pull/23
